### PR TITLE
Fix issue with product modal crashing because the webview is null at …

### PR DESCRIPTION
**Pull request by USMCFighter94**
…runtime

The activity_product layout was null at runtime, causing our app to crash when attempting to launch the Product modal

### CODE REVIEW

**Comment by USMCFighter94** [comment]
Hey guys,
This is a huge crash for us and I've had to manually import this library into our project in order to fix it, which has caused it's own share of problems. If this could get resolved quickly, that would be great.

**Comment by hectorups** [comment]
@USMCFighter94 first of all, sorry for the delay and thank you for the pr. 

Adding a `onClickListener` that opens a modal with the product info is something some users are expecting. You seem to have removed it which would solve the alleged npe but I'd like to keep the behavior. Can you tell me more about how to reproduce crash?

I'd like returning a `Spannable` rather than passing a `TextView`. It is something I'd like to add but I also want to keep the current behavior.

**Comment by USMCFighter94** [comment]
@hectorups My apologies, didn't realize that code was all in the same commit. I've made a new commit that re-adds the old code, but deprecates it. This way new and old implementations can live side by side.

As for the click listener crash, I removed it because our implementation requires that clicking on the promo text view launches a new flow to setup our app to use Affirm at checkout, and there is a separate help image that launches the product modal. I spent a full day trying to figure out why it was crashing, but could not. Setting the view to use activity_checkout layout stopped the crash, which again makes no sense because from what I can tell, they are exactly the same. That's all the info I can provide.

**Comment by hectorups** [comment]
@USMCFighter94 thank you again for the PR. 

I just did a small change on the `PromoCallback` interface to have the previous code 100% backwards compatible. Changes should be available on 1.0.7

**Comment by USMCFighter94** [comment]
@hectorups Thanks for doing that! I tried to update to 1.0.7, but it appears you only uploaded the POM file and not the AAR, so my apps fails to build. If you could get that published

**Comment by Nevvea7** [comment]
@USMCFighter94 Hey, unfortunately hector is on vacation in a far away place now, and after hours of searching we still can't find his credentials for uploading the AAR, so we suggest for now you can download the project, make it a module in your project, and once he comes back we can upload the AAR so you can swap it out then. Sorry about the trouble!

**Comment by USMCFighter94** [comment]
@Nevvea7 Ok. That is what I'm doing currently, but it breaks our CI builds, so I was hoping to get it switched over.
Thanks

**Comment by hectorups** [comment]
@USMCFighter94 1.0.8 is out and works. Sorry, for the inconvenience with 1.0.7

**Pull request merged**
